---
title: "IMT 573 Lab: Formulating Data Science Questions"
author: "Your Name Here"
date: "September 30th, 2019"
output: 
  tufte_handout:
    highlight: tango
---

# Collaborators: 

# \textbf{Instructions:}

In this lab activity you will practice thinking about  the data science process. Careful planning and defining project steps, as well as adapting to arising challenges, is vital for successful projects. With a small team (2-3 students), you will think about the following cases. For each case, consider the steps you would take to plan your project. Think about defining quantifiable goals, the data you need, and possible approaches to analysis. You team should write a short summary of your considerations and thoughts for each.

## Questions to data
1. \textbf{Team Formation:} Suppose your boss comes to you and says "We need to better understand team performance at our company. I want you to explore the characteristics of teams that perform optimally at solving problems." How might you go about exploring this research question?

Step:
-Obtain data->clean->explore->analysis->

Data:
-Team Performance data
-Managing Style/background;Team member background;Project Type;Salary;Working time;

-Observational

2. \textbf{Population Displacement After Disasters:} Suppose you work for the American Red Cross. Your job is to help determine where to send relief supplies, such as food, medicine and water, after a large-scale disaster. However, you know that when crises occur, people move to other, less damaged areas, perhaps to live temporarily with family or friends. How might you understand migration patterns following disasters?

3. \textbf{Predicting Patterns of Mobile Application Usage:} Suppose you are tasked with improving the user experience of a particular mobile phone operating system. Your team comes up with the idea to try to decrease the time it takes for applications on the phone to start. How might you understand typical application usage patterns? What additional data might you use to help predict what applications are going to be used next by a particular user?

Question to data:
-How much time it takes on average to start the applications on the phone?
-How do users feel about the OS?
-How much user experience will it improve if the time is decreased?
-What kind of application influence the user experience the most?

Data:
-average start time;Possible start time;Percentage of User satisfication; Goal of user satisfication;The difference between the specific OS and other OS;the average start time under other OS...



## Data to questions
1. \textbf{Random Acts of Pizza:} Consider a dataset with 5,671 textual requests for pizza and their outcome (successful/unsuccessful) from the Reddit community Random Acts of Pizza. All requests ask for the same thing - a free pizza - but each have their own unique characteristics. The meta-data for the requests is available and includes: time of the request, activity of the requester, community-age of the requester, up votes and down votes of the request, number of comments for the request, and the title of the request.

2. \textbf{Bike Sharing Systems:} Consider a dataset that contains the hourly and daily count of rental bikes between 2016 and 2018 in the Lime bikeshare system along with the corresponding weather and seasonal information. This data includes the date, season, holiday, day of the week, weather (clear, cloudy, snow, rain, etc), temperature, humidity, windspeed, and count of both casual and registered users of the bike share system.

3. \textbf{Titanic:} The sinking of the RMS Titanic is one of the most infamous shipwrecks in history. On April 15, 1912, during her maiden voyage, the Titanic sank after colliding with an iceberg, killing 1502 out of 2224 passengers and crew. This sensational tragedy shocked the international community and led to better safety regulations for ships. Consider a dataset that contains information about passengers, including survival, name, age, sex, ticket number, passenger fare, cabin, port of embarkation, and passenger class.

Possible goals:
-How many female servived?
-Is the survival rate ralated to the cabin number/sex/passenger class/age group?
-Is the age group that survive the most different in different passenger class?

Analysis Approach:
-Bar chart
